# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='temperature',
            field=models.IntegerField(default=1),
        ),
    ]
