# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(),
        ),
    ]
