# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180226_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('caffeine', models.DecimalField(decimal_places=2, max_digits=20)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=20)),
                ('picking', models.TextField()),
            ],
        ),
    ]
